import { useState, useEffect } from 'react'
import ReactMarkdown from 'react-markdown'
import { getLatestReport } from '../services/report'
import './ReportPage.css'

function ReportPage() {
  const [report, setReport]   = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState(null)

  useEffect(() => { loadReport() }, [])

  async function loadReport() {
    setLoading(true)
    setError(null)
    try {
      const data = await getLatestReport()
      setReport(data)
    } catch (err) {
      setError(err.message || 'Failed to load report.')
    } finally {
      setLoading(false)
    }
  }

  const formatDate = (d) => new Date(d).toLocaleString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
    hour: 'numeric', minute: '2-digit'
  })

  if (loading) return (
    <div className="report-page">
      <div className="page-top"><h1>Security Report</h1></div>
      <div className="report-state"><div className="spinner"></div><p>Loading latest report...</p></div>
    </div>
  )

  if (error) return (
    <div className="report-page">
      <div className="page-top"><h1>Security Report</h1></div>
      <div className="report-state">
        <div className="report-error">
          <p>{error}</p>
          <button onClick={loadReport} className="retry-btn">Retry</button>
        </div>
      </div>
    </div>
  )

  return (
    <div className="report-page">
      <div className="page-top">
        <h1>Security Report</h1>
        <p className="page-desc">
          AI-generated by Claude &mdash; {report?.generatedAt ? formatDate(report.generatedAt) : ''}
          {report?.workflowRunId && (
            <a
              href={`https://github.com/${"malinadettore"}/capstone-group3/actions/runs/${report.workflowRunId}`}
              target="_blank"
              rel="noopener noreferrer"
              className="run-link"
            >
              View pipeline run
            </a>
          )}
        </p>
      </div>
      <div className="report-body">
        <ReactMarkdown
          components={{
            span: ({ node, ...props }) => (
              <span {...props} />
            ),
            mark: ({ node, ...props }) => (
              <mark {...props} className="report-mark" />
            )
          }}
>
  {report?.markdown || ''}
</ReactMarkdown>

      </div>
    </div>
  )
}

export default ReportPage
